# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: brattcode
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-finalproject-typescript

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  profile: linus-test
  region: eu-north-1
  role: arn:aws:iam::586794465159:role/serverless-cloud

plugins:
  - serverless-plugin-typescript

package:
  individually: true

functions:
  createUser:
    handler: src/functions/signUp/index.main
    events:
      - httpApi:
          path: /signup
          method: post
  signIn:
    handler: src/functions/signIn/index.main
    events:
      - httpApi:
          path: /signin
          method: post
  postNote:
    handler: src/functions/postNote/index.main
    events:
      - httpApi:
          path: /create
          method: post
  getNote:
    handler: src/functions/getNote/index.main
    events:
      - httpApi:
          path: /get
          method: get
  updateNote:
    handler: src/functions/updateNote/index.main
    events:
      - httpApi:
          path: /update
          method: put
  deleteNote:
    handler: src/functions/deleteNote/index.main
    events:
      - httpApi:
          path: /delete
          method: delete
  getDeletedNotes:
    handler: src/functions/getDeletedNotes/index.main
    events:
      - httpApi:
          path: /getDeletedNotes
          method: get
  restoreNote:
    handler: src/functions/restoreNote/index.main
    events:
      - httpApi:
          path: /restore
          method: post

resources:
  Resources:
    userDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-dev
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    noteDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-db
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
          - AttributeName: isDeleted
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH 
          - AttributeName: noteId
            KeyType: RANGE 
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: isDeletedIndex
            KeySchema:
              - AttributeName: isDeleted
                KeyType: HASH
            Projection:
              ProjectionType: ALL