# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: brattcode
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-finalproject-typescript

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  profile: linus-test
  region: eu-north-1
  role: arn:aws:iam::586794465159:role/serverless-cloud

plugins:
  - serverless-plugin-typescript

package:
  individually: true

functions:
  createUser:
    handler: src/functions/signUp/index.handler
    events:
      - httpApi:
          path: /signup
          method: post
  signIn:
    handler: src/functions/signIn/index.handler
    events:
      - httpApi:
          path: /signin
          method: post
  postNote:
    handler: src/functions/postNote/index.main
    events:
      - httpApi:
          path: /createNote
          method: post
  getNote:
    handler: src/functions/getNote/index.main
    events:
      - httpApi:
          path: /getNotes
          method: get
  updateNote:
    handler: src/functions/updateNote/index.main
    events:
      - httpApi:
          path: /updateNote
          method: put

resources:
  Resources:
    userDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-dev
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    noteDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-db
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S 
        KeySchema:
          - AttributeName: userId
            KeyType: HASH 
          - AttributeName: noteId
            KeyType: RANGE 
        BillingMode: PAY_PER_REQUEST